#+TITLE: ii Install and Configuration of Spac(emacs)

[[http://spacemacs.org/][Spacemacs]] with a number of [[https://www.gnu.org/software/emacs/][Emacs]] packages is at the center of our workflow.
The goal is to help future users of this workflow to get setup with the least amount of frustration and feeling productive.

> Spacemacs is a new way to experience Emacs -- a sophisticated and polished set-up focused on ergonomics, mnemonics and consistency.

* Emacs

Our config focuses on the stable 26.2 release of emacs, install as appropriate for your OS.
You can follow the directions at the bottom of this document if you want to build from source.

** ELPA Mirror

To save time we will setup a local mirror for all the LISP files that we need as part of spacemacs.
Depending on your machine and internet connection it may take some time to download, configure and compile.

#+BEGIN_SRC shell
sudo git clone --depth 1 -b 26.2-stable \
    https://github.com/ii/elpa-mirror \
    /usr/local/elpa-mirror
#+END_SRC

** Configuring Emacs

You will need to determine which use case below best fits your needs. It could save you a lot of time debugging your future setup.

*** Setup for an the current user

As the current user has already been created we can't use the setup in the `/etc/skel` folder.
The configuration below will use the user's home folder.

#+BEGIN_SRC shell
git clone --depth 1 -b 26.2-stable --recurse-submodules \
     https://github.com/ii/spacemacs.git \
     ~/.emacs.d \
   && ln -sf ~/.emacs.d/private/local/dot-spacemacs/.spacemacs ~/.spacemacs \
   && emacs --batch -l ~/.emacs.d/init.el
#+END_SRC


*** New user accounts

If you want all future users to have this working config, setting up Spacemacs into `/etc/skel` folder, which get's copied into a users homedir on user creation.

**** Step 1

Download and link spacemacs inside the `/etc/skel` folder.

#+BEGIN_SRC shell
git clone --depth 1 -b 26.2-stable --recurse-submodules \
    https://github.com/ii/spacemacs.git \
    /etc/skel/.emacs.d \
  && ln -s .emacs.d/private/local/dot-spacemacs/.spacemacs /etc/skel/.spacemacs
#+END_SRC

**** Step 2

As the `root` user we need to process `init.el` for future user accounts.

#+BEGIN_SRC shell
sudo -s
ln -sf /etc/skel/.emacs.d /root/.emacs.d \
  && ln -sf /root/.emacs.d/private/local/dot-spacemacs/.spacemacs /root/.spacemacs \
  && HOME=/root emacs --batch -l /root/.emacs.d/init.el \
  && rm /root/.emacs.d /root/.spacemacs \
  && rm /etc/skel/.emacs.d/elpa/gnupg/S.gpg-agent*
exit
#+END_SRC


* From Source
** Get 26.2 stable version

Using `git` download the current *stable* version of Emacs

#+BEGIN_SRC shell
cd /tmp
wget https://ftp.gnu.org/gnu/emacs/emacs-26.2.tar.gz
tar xfz emacs-26.2.tar.gz
#+END_SRC

** Build & Install Emacs

**Step 1:** Install the following packages so that we can build Emacs (on Ubuntu/Debian)

#+BEGIN_SRC shell
sudo apt install \
    autoconf make gcc texinfo \
    libgtk-3-dev libxpm-dev libjpeg-dev \
    libgif-dev libtiff5-dev libgnutls28-dev libncurses5-dev
#+END_SRC

**Step 2:** Follow the commands below as Emacs is built and then installed

#+BEGIN_SRC 
cd /tmp/emacs-26.2/
./autogen.sh
./configure
make
sudo make install
#+END_SRC

** Check Emacs version

The current version should be `26.2`

#+BEGIN_SRC shell :results code
emacs --version
#+END_SRC

#+RESULTS:
#+BEGIN_SRC shell
GNU Emacs 26.2
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
#+END_SRC

* References

- [[https://github.com/ii/spacemacs/tree/stable][Github: ii/spacemacs (stable)]] 
- [[https://magit.vc/manual/forge/][Magit: Forge]] 
- [[https://gitlab.ii.coop/ii/tooling/ob-tmate][ob-tmate]] 
